# Generated by Django 2.2.3 on 2019-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnover', models.IntegerField()),
                ('amount_year', models.IntegerField()),
                ('amount_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('city_province', models.CharField(max_length=20)),
                ('city_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('city_year', models.IntegerField()),
                ('city_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_postID', models.IntegerField()),
                ('comment_customerID', models.IntegerField()),
                ('comment_time', models.CharField(max_length=50)),
                ('comment_content', models.CharField(max_length=500)),
                ('comment_thumbUp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_districtID', models.IntegerField()),
                ('community_location', models.CharField(max_length=150)),
                ('community_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('community_name', models.CharField(max_length=20)),
                ('usage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_name', models.CharField(max_length=50)),
                ('customers_Password', models.CharField(max_length=50)),
                ('charger', models.SmallIntegerField(choices=[(1, '管理员'), (2, '普通用户')], default=2)),
                ('headImage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_cityID', models.IntegerField()),
                ('district_name', models.CharField(max_length=20)),
                ('instantPrice', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.CharField(max_length=10)),
                ('post_name', models.CharField(max_length=50)),
                ('post_content', models.CharField(max_length=500)),
                ('post_thumbUp', models.IntegerField()),
                ('post_comment', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='customers',
        ),
    ]
