# Generated by Django 2.2.3 on 2019-07-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190703_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customers_Password',
            new_name='customer_Password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customers_name',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='charger',
            field=models.SmallIntegerField(choices=[(2, '普通用户'), (1, '管理员')], default=2),
        ),
    ]
