# Generated by Django 2.2.3 on 2019-07-03 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190703_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='districtCityID',
        ),
        migrations.AddField(
            model_name='district',
            name='districtCityName',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
