# Generated by Django 2.2.3 on 2019-07-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190703_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='charger',
            field=models.SmallIntegerField(choices=[(1, '管理员'), (2, '普通用户')], default=2),
        ),
        migrations.AlterField(
            model_name='district',
            name='instantPrice',
            field=models.IntegerField(),
        ),
    ]
