# Generated by Django 2.2.3 on 2019-07-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190704_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='communityDistrictID',
        ),
        migrations.AlterField(
            model_name='customer',
            name='charger',
            field=models.SmallIntegerField(choices=[(2, '普通用户'), (1, '管理员')], default=2),
        ),
    ]
