# Generated by Django 2.2.3 on 2019-07-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190705_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='charger',
            field=models.SmallIntegerField(choices=[(2, '普通用户'), (1, '管理员')], default=2),
        ),
    ]
