# Generated by Django 2.2.3 on 2019-07-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190705_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='communityDistrictID',
        ),
        migrations.AddField(
            model_name='community',
            name='communityDistrictName',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='charger',
            field=models.SmallIntegerField(choices=[(2, '普通用户'), (1, '管理员')], default=2),
        ),
    ]
