# Generated by Django 2.2.3 on 2019-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190706_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postComment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='postThumbUp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.CharField(default='00:00:00', max_length=50),
        ),
    ]
