# Generated by Django 2.2.3 on 2019-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190706_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='linkRelativeRatio',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='yearOnYearRatio',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='district',
            name='districtMonth',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='district',
            name='districtYear',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='district',
            name='linkRelativeRatio',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='district',
            name='yearOnYearRatio',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='charger',
            field=models.SmallIntegerField(choices=[(1, '管理员'), (2, '普通用户')], default=2),
        ),
    ]
