# Generated by Django 2.2.3 on 2019-07-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190711_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.CharField(default='2019-07-13 05:41:17', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.CharField(default='2019-07-13 05:41:17', max_length=50),
        ),
    ]
